// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owbpgdavvrtwqnoxdfvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93YnBnZGF2dnJ0d3Fub3hkZnZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTMzMDQsImV4cCI6MjA2NTIyOTMwNH0.htWjEYPQC9DwsSpgiOQIHsBEZM0TCrQWd4R5f7hjyVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);